# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
workspace 'Moder'


target 'Moder' do
pod 'Skeets', '~> 0.9.2'
end

target 'ModerTests' do

end

